server:
  port: 8080

spring:
  application:
    name: bank-springboot-base-db-jdbc
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/icangjinge_jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver