-- -- 创建数据库
-- CREATE DATABASE icangjinge_jdbc DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
--
-- USE icangjinge_jdbc;
-- -- 账户表
-- CREATE TABLE Account(
--  ACNO VARCHAR(32) NOT NULL,
--  ACNAME VARCHAR(256) NOT NULL,
--  IDNO VARCHAR(32) NOT NULL,
--  STATUS CHAR(2) DEFAULT '00' COMMENT '00-正常,01-冻结,02-挂失',
--  CREATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
--  UPDATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
--  PRIMARY KEY (ACNO)
-- );
--


-- 创建数据库
CREATE DATABASE icangjinge_write_jdbc DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE icangjinge_write_jdbc;
-- 账户表
CREATE TABLE Account(
 ACNO VARCHAR(32) NOT NULL,
 ACNAME VARCHAR(256) NOT NULL,
 IDNO VARCHAR(32) NOT NULL,
 STATUS CHAR(2) DEFAULT '00' COMMENT '00-正常,01-冻结,02-挂失',
 CREATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 UPDATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
 PRIMARY KEY (ACNO)
);