server:
  port: 8081

spring:
  application:
    name: bank-springboot-base-db-mybatis
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/icangjinge_mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver
#打印sql
logging:
  level:
    com.icangjinge.bank.springboot.base.persistence: DEBUG
mybatis:
  mapper-locations: classpath:META-INF/mappers/*.xml